# NumPy opdrachten & uitwerkingen

# Opdracht 1: BMI

In het bestand `student_data.txt` staat informatie over studenten.

a) Maak een array met de gewichten van de studenten.<br>
b) Maak een array met de lengtes van de studenten.<br>
c) Maak een array met de BMI (=gewicht/lengte^2) van de studenten en print deze uit.<br>
d) Print de laagste en de hoogste BMI, de gemiddelde BMI en de standaarddeviatie.

Data van een nieuwe student komt binnen; 96 kg en 1.88 m.<br>
e) Vul de arrays met de gewichten, lengtes en BMI aan met de gegevens van de nieuwe student.<br>
f) Print de BMI van de nieuwe student.<br>
g) Print de nieuwe gemiddelde BMI over alle studenten.


In [1]:
import numpy as np

studenten = np.loadtxt('student_data.txt', skiprows=1)
gewicht = studenten[:,2]
lengte = studenten[:,3]
bmi = gewicht / lengte**2
print ("BMI array:", bmi)
print ("Min, max, mean en std:", bmi.min(), bmi.max(), bmi.mean(), bmi.std())

gewicht = np.append(gewicht, [96])
lengte = np.append(lengte, [1.88])
bmi = gewicht / lengte**2
print ("BMI:", bmi[-1])
print ("Nieuwe gemiddelde BMI:", bmi.mean())

BMI array: [23.79552644 26.54320988 17.95918367 24.09297052 20.9572742  20.99054097
 25.76298058 22.78330889 21.51385851 22.24392361]
Min, max, mean en std: 17.959183673469386 26.54320987654321 22.664277727206713 2.394503224554205
BMI: 27.16161158895428
Nieuwe gemiddelde BMI: 23.073126260092856


# Opdracht 2: array splitsen

a) Creëer een 2D-array van 6 rijen en 9 kolommen met random getallen.<br>
b) Split de array in 3 kleinere 2D-arrays van 6 rijen en 3 kolommen.<br>
c) Split de array gecreëerd bij a in 3 kleinere 2D-arrays van 2 rijen en 9 kolommen.


In [2]:
grote_matrix = np.random.random((6,9)) # 6 rijen, 9 kolommen
print("Grote matrix:", grote_matrix)
print("Shape grote matrix:", grote_matrix.shape)

grote_matrix_hsplit = np.hsplit(grote_matrix,3) # Geeft een array van 3 arrays
print("\nMatrices hsplit:", grote_matrix_hsplit)
print("Shape matrix hsplit[0] shape:", grote_matrix_hsplit[0].shape) # 6 rijen, 3 kolommen

grote_matrix_vsplit = np.vsplit(grote_matrix,3)
print("\nMatrices vsplit:", grote_matrix_vsplit)
print("Shape matrix vsplit[0] shape:", grote_matrix_vsplit[0].shape) # 2 rijen, 9 kolommen

Grote matrix: [[0.12224385 0.10261363 0.15332592 0.41011533 0.63975138 0.36712071
  0.36000349 0.02741718 0.20914836]
 [0.92936646 0.18930453 0.78819978 0.6528742  0.24043129 0.10254463
  0.42370822 0.30053135 0.31775833]
 [0.15889652 0.72345879 0.2075992  0.48946634 0.73914349 0.55119725
  0.95342569 0.23640161 0.89201903]
 [0.24191069 0.82207051 0.12440082 0.07861468 0.91507922 0.43953221
  0.6525228  0.48639407 0.29142111]
 [0.82676568 0.25618351 0.18237127 0.94475822 0.44408924 0.72171832
  0.41205124 0.32631556 0.47637231]
 [0.28227565 0.10619029 0.51505867 0.15977071 0.11039092 0.81045992
  0.83855082 0.32214464 0.93463255]]
Shape grote matrix: (6, 9)

Matrices hsplit: [array([[0.12224385, 0.10261363, 0.15332592],
       [0.92936646, 0.18930453, 0.78819978],
       [0.15889652, 0.72345879, 0.2075992 ],
       [0.24191069, 0.82207051, 0.12440082],
       [0.82676568, 0.25618351, 0.18237127],
       [0.28227565, 0.10619029, 0.51505867]]), array([[0.41011533, 0.63975138, 0.36712071]

# Opdracht 3: kwadraten array

a) Vul een 2D-array van 10 rijen en 10 kolommen met het kwadraat van de getallen 0 t/m 99. (Dit kan in 1 regel.)<br>
b) Print de array uit.

In [3]:
kwadraten = np.arange(100).reshape(10,10) ** 2
print ("Kwadraten array:", kwadraten)

Kwadraten array: [[   0    1    4    9   16   25   36   49   64   81]
 [ 100  121  144  169  196  225  256  289  324  361]
 [ 400  441  484  529  576  625  676  729  784  841]
 [ 900  961 1024 1089 1156 1225 1296 1369 1444 1521]
 [1600 1681 1764 1849 1936 2025 2116 2209 2304 2401]
 [2500 2601 2704 2809 2916 3025 3136 3249 3364 3481]
 [3600 3721 3844 3969 4096 4225 4356 4489 4624 4761]
 [4900 5041 5184 5329 5476 5625 5776 5929 6084 6241]
 [6400 6561 6724 6889 7056 7225 7396 7569 7744 7921]
 [8100 8281 8464 8649 8836 9025 9216 9409 9604 9801]]
