# NumPy opdrachten

# Opdracht 1: BMI

In het bestand `student_data.txt` staat informatie over studenten.

a) Maak een array met de gewichten van de studenten.<br>
b) Maak een array met de lengtes van de studenten.<br>
c) Maak een array met de BMI (=gewicht/lengte^2) van de studenten en print deze uit.<br>
d) Print de laagste en de hoogste BMI, de gemiddelde BMI en de standaarddeviatie.

Data van een nieuwe student komt binnen; 96 kg en 1.88 m.<br>
e) Vul de arrays met de gewichten, lengtes en BMI aan met de gegevens van de nieuwe student.<br>
f) Print de BMI van de nieuwe student.<br>
g) Print de nieuwe gemiddelde BMI over alle studenten.


In [36]:
import numpy as np
studenten_data = np.loadtxt("student_data.txt", skiprows=1)
length_student = studenten_data[:,3]
weight_student = studenten_data[:,2]
BMI_student = weight_student/length_student ** 2
print("BMI", BMI_student)
print("Lowest bmi", np.min(BMI_student), "Heighest bmi", np.max(BMI_student), "average", np.average(BMI_student), "standard deviation", np.std(BMI_student))
print(weight_student)
weight_student = np.append(weight_student, [96])
length_student = np.append(length_student, [1.88])
BMI_student = weight_student/length_student ** 2
print(BMI_student[-1])
print(np.average(BMI_student))

BMI [23.79552644 26.54320988 17.95918367 24.09297052 20.9572742  20.99054097
 25.76298058 22.78330889 21.51385851 22.24392361]
Lowest bmi 17.959183673469386 Heighest bmi 26.54320987654321 average 22.664277727206713 standard deviation 2.394503224554205
[85. 86. 55. 68. 62. 79. 78. 73. 60. 82.]
27.16161158895428
23.073126260092856


# Opdracht 2: array splitsen

a) Creëer een 2D-array van 6 rijen en 9 kolommen met random getallen.<br>
b) Split de array in 3 kleinere 2D-arrays van 6 rijen en 3 kolommen.<br>
c) Split de array gecreëerd bij a in 3 kleinere 2D-arrays van 2 rijen en 9 kolommen.


In [46]:
new_arr = np.random.random((6,9))
print(new_arr)
small_array = np.hsplit(new_arr,3)
print(small_array)
smallest_array = np.vsplit(new_arr,3)

[[0.94171008 0.92276875 0.94543646 0.81085762 0.04008397 0.41385032
  0.60280784 0.93322998 0.2988979 ]
 [0.3955498  0.52211739 0.41827775 0.15646996 0.51883482 0.04021917
  0.19545427 0.92234608 0.18461775]
 [0.61474761 0.06765788 0.31202238 0.01892362 0.6888163  0.99098849
  0.21012403 0.09258228 0.45825666]
 [0.82856604 0.61470509 0.31181066 0.35542094 0.37481609 0.94826657
  0.89204057 0.02514478 0.17586457]
 [0.20745633 0.42145748 0.34110716 0.92436451 0.50783489 0.38334992
  0.43253228 0.55715524 0.89949656]
 [0.39946545 0.30600701 0.40244364 0.72596953 0.33511211 0.50917877
  0.00113907 0.33646669 0.10747842]]
[array([[0.94171008, 0.92276875, 0.94543646],
       [0.3955498 , 0.52211739, 0.41827775],
       [0.61474761, 0.06765788, 0.31202238],
       [0.82856604, 0.61470509, 0.31181066],
       [0.20745633, 0.42145748, 0.34110716],
       [0.39946545, 0.30600701, 0.40244364]]), array([[0.81085762, 0.04008397, 0.41385032],
       [0.15646996, 0.51883482, 0.04021917],
       [0.01

# Opdracht 3: kwadraten array

a) Vul een 2D-array van 10 rijen en 10 kolommen met het kwadraat van de getallen 0 t/m 99. (Dit kan in 1 regel.)<br>
b) Print de array uit.

In [47]:
sq_arr = np.arange(100).reshape(10,10) ** 2
print(sq_arr)

[[   0    1    4    9   16   25   36   49   64   81]
 [ 100  121  144  169  196  225  256  289  324  361]
 [ 400  441  484  529  576  625  676  729  784  841]
 [ 900  961 1024 1089 1156 1225 1296 1369 1444 1521]
 [1600 1681 1764 1849 1936 2025 2116 2209 2304 2401]
 [2500 2601 2704 2809 2916 3025 3136 3249 3364 3481]
 [3600 3721 3844 3969 4096 4225 4356 4489 4624 4761]
 [4900 5041 5184 5329 5476 5625 5776 5929 6084 6241]
 [6400 6561 6724 6889 7056 7225 7396 7569 7744 7921]
 [8100 8281 8464 8649 8836 9025 9216 9409 9604 9801]]
